version: '3'
services:
    web:
        build: .
        depends_on:
            - db
        ports:
            - 8080:8080
    db:
        image: mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: noteit
            MYSQL_USER: noteit
            MYSQL_PASSWORD: noteit
            MYSQL_ROOT_PASSWORD: password